spring:
  main:
    banner-mode: "off"

server.port: ${PORT:8080}

logging.level:
  ROOT: DEBUG

spring.profiles: color

spring.output.ansi.enabled: ALWAYS

---

spring.profiles: dev

logging.level:
  studio.styx: DEBUG

---
azure:
  cosmosdb:
    uri: https://chainreaction-server-db.documents.azure.com:443/
    key: iOgJSffolWvtGX8IDfAAknA2PsLJbvyX5tXoO4ht4Ndr6wBi5gCB0N3Jkin063nbd9uc7cLxuWXW4cT5vl5IPA==
    database: chainreaction-server-db-object
---