spring:
  main:
    banner-mode: "off"

server.port: ${PORT:8080}

logging.level:
  ROOT: DEBUG

spring.profiles: color

spring.output.ansi.enabled: ALWAYS

---

spring.profiles: dev

logging.level:
  studio.styx: DEBUG